POST http://localhost:3000/notes
Content-Type: application/json

{
    "title": "Build Dguhjk",
    "content":"Build a capable of holding 40000 litres"

    //"UpdatedAt":"2021-07-25"
}

### GET ALL PROJECTS
GET http://localhost:3000/notes

### GET ONE PROJECT
GET http://localhost:3000/notes/15994ef2-0faa-49dd-b7ca-b446dd23824d

### UPDATING PROJECT
PUT http://localhost:3000/notes/15994ef2-0faa-49dd-b7ca-b446dd23824d
Content-Type: application/json


    {
    "title": "Jesso",
    "content":" capable of holding 40000 litres",
    "createdAt":"Nyeruko"
    
}


###
DELETE http://localhost:3000/notes/15994ef2-0faa-49dd-b7ca-b446dd23824d