POST http://localhost:3000/notes
Content-Type: application/json

{
    "title": "Build Dguhjk",
    "content":"Build a capable of holding 40000 litres"

    //"UpdatedAt":"2021-07-25"
}

### GET ALL PROJECTS
GET http://localhost:3000/notes

### GET ONE PROJECT
GET http://localhost:3000/notes/fe78f67e-2dc7-4646-913a-3c3026bf2d35

### UPDATING PROJECT
PUT http://localhost:3000/notes/fe78f67e-2dc7-4646-913a-3c3026bf2d35
Content-Type: application/json


    {
    "title": "Jesso",
    "content":" capable of holding 40000 litres",
    "createdAt":"Nyeruko"
    
}


###
DELETE http://localhost:3000/notes/fe78f67e-2dc7-4646-913a-3c3026bf2d35